config/routes.rb
Rails.application.routes.draw do

  root to: 'bookmarks#index'

  devise_for :users,
    controllers: {
      registrations: 'registrations'
    }

  resources :users

  resources :feeds, only: [:index]
  resources :lists

  resources :collections
  resources :bookmarks do
    member do
      get 'regenerate', to: 'bookmarks#regenerate'
    end
  end

  resources :tags, only: [:index, :show, :edit], controller: :bookmarks, action: :index
end

app/models/collection.rb
class Collection < ActiveRecord::Base

  has_attached_file :icon,
                    storage: :s3,
                    s3_credentials: "#{Rails.root}/config/aws_s3.yml",
                    styles: {
                      xs: ['12x12#', :png],
                      lg: ['100x100#', :png]
                    }

  do_not_validate_attachment_file_type :icon

  # Associations

  belongs_to :user

  has_and_belongs_to_many :bookmarks

  # Methods

  #########
  # Gets all the Collections created by the User as Owner
  #
  # @param: owner_id
  #
  def self.for_owner(owner)
    owner.collections
  end

  #########
  # Gets all the Collections that the User is subscribed to
  #
  # @param: user_id
  #
  def self.for_user(user)
    includes(:users).where(collections_users:
      { user: user })
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  # GET /collections
  def index
    @collections = Collection.paginate(page: params[:page])
  end

  # GET /collections/:id
  def show
    collection
    @bookmarks = collection.bookmarks.paginate(page: params[:page])
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/:id/edit
  def edit
    collection

    render template: 'collections/_form'
  end

  # POST /collections
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/:id
  def update
    respond_to do |format|
      if collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/:id
  def destroy
    collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(
        :user_id,
        :name,
        :description,
        :public,
        :icon,
        user_ids: [],
        bookmark_ids: []
      )
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper

  def collection_image_presenter(c)
    icon = c.icon.exists?

    content_tag(:div, class: "bit-collection-image bit-collection-image-#{icon}") do
      if icon
        concat(image_tag(c.icon(:lg), class: 'img-responsive'))
      end
    end
  end

  def collection_bookmarks_presenter(layout, id, bookmarks)
    max_bookmarks = 10

    if layout && !bookmarks.nil?

      bookmarks_curator = bookmarks.map { |b| link_to(image_tag(b.snapshot(:sm), title: b.name, data: { toggle: 'tooltip', placement: 'top'}), bookmark_path(b)) }

      if bookmarks.length > max_bookmarks
        first_set = bookmarks_curator.first(max_bookmarks)
        last_set  = link_to("#{bookmarks.count - max_bookmarks} more..", collection_path(id), class: 'tag badge-primary')

        _bookmarks = first_set.insert(max_bookmarks, last_set)
      else
        _bookmarks = bookmarks_curator
      end


      content_tag(:div, class: 'bit-association bit-association-bookmarks') do
        _bookmarks.join.html_safe
      end
    end
  end
end

app/views/collections/_collections.slim
.grid

  - collection.each do |c|

    .grid-cell.grid-cell-xs-12.grid-cell-sm-6.grid-cell-md-4.grid-cell-lg-3
      .bit-collection class="bit-collection-public-#{c.public}"
        .grid
          .grid-cell.grid-cell-sm-12
            .bit-collection-url
              h1
                = link_to c.name, collection_path(c)

        .grid
          .grid-cell.grid-cell-sm-12
            = collection_image_presenter(c)

        .grid
          .grid-cell.grid-cell-sm-12
            .bit-collection-description
              = description_presenter(c.description)

        .bit-collection-actions
          .grid
            .grid-cell.grid-cell-sm-8
              = collection_bookmarks_presenter(full_layout, c.id, c.bookmarks)

            .grid-cell.grid-cell-sm-4
              = link_to fa_icon("pencil"), edit_collection_path(c)
              = link_to fa_icon("trash-o"), collection_path(c), method: :delete, confirm: { message: "Are you sure?"} unless c.public?

app/views/collections/_form.html.slim
= simple_form_for @collection, remote: true, html: { id: 'photoinfo', multipart: true } do |f|
  = token_tag form_authenticity_token
  = f.input :owner_id, as: :hidden, input_html: { value: current_user.id }

  .row
    .col-sm-8
      h4
        = @collection.new_record? ? "New Collection" : "Edit <span>#{@collection.name}</span> Collection".html_safe

    .col-sm-4
      .form-group
        = f.input_field :public, as: :boolean, checked_value: true, unchecked_value: false, data: { labelauty: "Don't make this Collection public|Make this Collection public" }, class: 'labelauty'

  .row
    .col-sm-12
      = f.error_notification

  .row
    .col-sm-6
      .row
        .col-sm-4.collection-form-icon
          .row
            .col-sm-12
              #image-upload.collection-form-icon__preview class="collection-form-icon__#{@collection.icon?}"

                - if @collection.icon?

                  = image_tag @collection.icon(:original), class: 'collection-form-icon__preview'

                - else

                  = fa_icon('upload', class: 'hide-preview')

                  p.hide-preview
                    = 'Upload an Icon'

              = f.input_field :icon, id: 'image-upload-input', accept: 'image/png,image/gif,image/jpeg, image/jpg'

          .row
            .col-sm-12
              .form-actions
                = f.button :submit

        .col-sm-8
          .form-group.collection-form-name
            = f.input_field :name, class: 'form-control input-lg input-booky'
            = f.label :name, class: 'label-booky'
              span.label-booky__content
                = "Name"

          .form-group.collection-form-description
            = f.input_field :description, class: 'form-control input-lg input-booky'
            = f.label :description, class: 'label-booky'
              span.label-booky__content
                = "Description"

    .col-sm-6
      = f.association :bookmarks, as: :select, label: false, input_html: { class: 'magicsuggest' }

app/views/collections/index.html.slim
.grid
  .grid-cell.grid-cell-sm-2

  .grid-cell.grid-cell-sm-10

    - if @collections.empty?

      .alert.alert-info
        = "You have no collections, why not #{link_to 'add one', new_collection_path }".html_safe

    - else

      .grid
        .grid-cell.grid-cell-sm-12
          .main-content-affix data-spy="affix" data-offset-top="70"
            = will_paginate(@collections, inner_window: 1, outer_window: 3)

      .grid
        .grid-cell.grid-cell-sm-12
          == render partial: 'collections', locals: { full_layout: true, collection: @collections }

app/views/collections/new.html.slim
== render 'form'

app/views/collections/show.html.slim
.row
  .col-sm-3
    .row
      .col-sm-12
        .main-nav-affix data-spy="affix" data-offset-top="70"

          .row
            .col-sm-2
              .booqmarkit-image
                = image_tag @collection.icon(:original), class: 'img-responsive'

            .col-sm-10
              h1.booqmarkit-url
                = @collection.name

              = description_presenter(@collection.description)

          .row
            .col-sm-12
              h5.presentation
                = "Collection Stats"

          .row
            .col-sm-3
              = @collection.bookmarks_count

            .col-sm-3


  .col-sm-9
    .row
      .col-sm-12
        .main-content-affix data-spy="affix" data-offset-top="70"
          .row
            .col-sm-9
              = will_paginate(@bookmarks, inner_window: 1, outer_window: 3)

            .col-sm-3.text-right
              = link_to "New Bookmark", new_bookmark_path, class: 'btn btn-sm btn-primary'

    .row
      .col-sm-12
        == render partial: 'bookmarks/bookmarks', locals: { collection: @bookmarks }