config/routes.rb
Rails.application.routes.draw do

  root to: 'bookmarks#index'

  devise_for :users,
    controllers: {
      registrations: 'registrations'
    }

  resources :users

  resources :feeds, only: [:index]
  resources :lists

  resources :collections
  resources :bookmarks do
    member do
      get 'regenerate', to: 'bookmarks#regenerate'
    end
  end

  resources :tags, only: [:index, :show, :edit], controller: :bookmarks, action: :index
end

app/models/list.rb
class List < ActiveRecord::Base

  has_attached_file :icon,
                    storage: :s3,
                    s3_credentials: "#{Rails.root}/config/aws_s3.yml",
                    styles: {
                      xs: ['12x12#', :png],
                      lg: ['100x100#', :png]
                    }

  do_not_validate_attachment_file_type :icon

  has_one :user, foreign_key: 'owner_id'

  has_and_belongs_to_many :users
  has_and_belongs_to_many :bookmarks
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/1
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lists/1
  def update
    if @list.update(list_params)
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def list_params
      params[:list]
    end
end

app/views/lists/_form.html.slim
= simple_form_for(@list) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/lists/edit.html.slim
h1 Editing list

== render 'form'

= link_to 'Show', @list
'|
= link_to 'Back', lists_path

app/views/lists/index.html.slim
h1 Listing lists

table
  thead
    tr
      th
      th
      th

  tbody
    - @lists.each do |list|
      tr
        td = link_to 'Show', list
        td = link_to 'Edit', edit_list_path(list)
        td = link_to 'Destroy', list, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New List', new_list_path

app/views/lists/new.html.slim
h1 New list

== render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.slim
p#notice = notice


= link_to 'Edit', edit_list_path(@list)
'|
= link_to 'Back', lists_path