config/routes.rb
Rails.application.routes.draw do

  root to: 'bookmarks#index'

  devise_for :users,
    controllers: {
      registrations: 'registrations'
    }

  resources :users

  resources :feeds, only: [:index]
  resources :lists

  resources :collections
  resources :bookmarks do
    member do
      get 'regenerate', to: 'bookmarks#regenerate'
    end
  end

  resources :tags, only: [:index, :show, :edit], controller: :bookmarks, action: :index
end

app/views/shared/_footer.slim
.grid-container
  .grid

    .grid-cell.grid-cell-sm-5
      p.meta
        = "Crafted with ♥ &amp; maintained by #{link_to 'Studio51', 'http://www.creative-studio51.co.uk'} &copy; 2015".html_safe

    .grid-cell.grid-cell-sm-4
      ul.bit-nav.bit-nav-list
        li
          = link_to "About", ""
        li
          = link_to "F.A.Q", ""
        li
          = link_to "Terms &amp; Conditions".html_safe, ""
        li
          = link_to "Get involved", "https://github.com/studio51/app-booqmark.it"

    .grid-cell.grid-cell-sm-3
      .bit-support-actions
        button type="button" class="bit-btn bit-btn-small bit-btn-success" data-toggle="modal" data-target=".donations-modal"
          = fa_icon("money", text: "Support Booqmark.it")

        button type="button" class="bit-btn bit-btn-small bit-btn-primary" data-toggle="modal" data-target=".feedback-modal"
          = fa_icon("bullhorn")

.modal.fade.donations-modal role="dialog" aria-labelledby="donationsLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        h4#donationsLabel.modal-title
          = "Support Booqmark.it"

      .modal-body
        p
          = "Thank you for considering supporting Booqmark.it"

        p
          / Booqmark.it will always be free and wether you decide to support us
          / or not, we won't restrict anything.
          / We do however, need help in paying the AWS bills and ensuring continous
          / development.
          / All the money we receive from donations cover our AWS bills
          = "We use the donations we receive from our users to develop new features and pay our Amazon AWS bills"


.modal-footer.modal.fade.feedback-modal role="dialog" aria-labelledby="donationsLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        h4#donationsLabel.modal-title
          = "Feedback &amp; Suggestions".html_safe

      .modal-body
        p
          = "Thank you for helping us through the BETA stage. Stay awesome!"

        p
          = "We're working hard to implement a Feedback system. Until then please email your query to booqmarkit@creative-studio51.co.uk"

      .modal-footer

app/views/shared/_header.slim
nav.bit-navbar role="navigation"
  .grid-container
    .grid
      .bit-grid--navbar-brand
        = link_to image_tag("logo-bold.svg", title: t("app.description"), alt: t("app.name"), class: "img-responsive"), root_path, class: "bit-brand grid-cell-middle"

      .bit-grid--navbar-search__user
        .grid
          .bit-grid--navbar-search
            .input-addon
              span.input-addon-item
                = fa_icon("search")
              = text_field_tag :q, params[:q], class: 'input input-addon-field', placeholder: 'Search Collections, Bookmarks, Tags and Users..', aria: { describedby: "search-icon" }

          .bit-grid--navbar-user
            ul.bit-navbar-user
              = user_presenter(current_user)

              li.user-name.hidden-xs.hidden-sm
                = link_to current_user.name, user_path(current_user.id)

              li.dropdown
                = link_to fa_icon("angle-down"), '#', class: "dropdown-toggle", data: { toggle: "dropdown" }, role: "button"

                ul.dropdown-menu role="menu"
                  li.user-name.visible-sm
                    = link_to current_user.name, user_path(current_user.id)

                  li
                    = link_to fa_icon("cogs", text: "Settings")

                  li.divider

                  li
                    = link_to fa_icon("sign-out", text: "Logout"), destroy_user_session_path, method: :delete

.grid
  .grid-cell.grid-cell-sm-12
    .grid-container
      = render partial: "shared/navigation"

app/views/shared/_navigation.slim
.grid
  .grid-cell.grid-cell-sm-1
    = link_to "Back", :back

  .grid-cell.grid-cell-sm-offset-1.grid-cell-sm-2
    h5.heading
      = "Public Activity"

    ul.bit-nav.bit-nav-list.bit-nav-main
      li
        = link_to fa_icon("rss", text: "Feed"), feeds_path, class: 'bit-nav-links bit-btn bit-btn-block bit-btn-small bit-btn-danger'

      li
        = link_to fa_icon("list", text: "Lists"), lists_path, class: 'bit-nav-links bit-btn bit-btn-block bit-btn-small bit-btn-info'

  .grid-cell.grid-cell-sm-offset-1.grid-cell-sm-3
    h5.heading
      = "My Activity"

    ul.bit-nav.bit-nav-list.bit-nav-main
      li
        = link_to fa_icon("folder", text: "Collections"), collections_path, class: 'bit-nav-links bit-btn bit-btn-block bit-btn-small bit-btn-primary'

        .bit-nav-element-addon
          = link_to fa_icon("plus"), new_collection_path, class: 'bit-nav-button'

      li
        = link_to fa_icon("bookmark", text: "Bookmarks"), bookmarks_path, class: 'bit-nav-links bit-btn bit-btn-block bit-btn-small bit-btn-success'

        .bit-nav-element-addon
          = link_to fa_icon("plus"), new_bookmark_path, class: 'bit-nav-button'